lexCurrentNode :lNo  :token       :valIfNo   :pNode                    :IsLeaf(y/n) :nodeSymbol          
declare        :1    :DECLARE     :n         :moduleDeclaration        :y           :DECLARE             
n              :n    :n           :n         :moduleDeclarations       :n           :moduleDeclaration   
module         :1    :MODULE      :n         :moduleDeclaration        :y           :MODULE              
compute        :1    :ID          :n         :moduleDeclaration        :y           :ID                  
;              :1    :SEMICOL     :n         :moduleDeclaration        :y           :SEMICOL             
n              :n    :n           :n         :program                  :n           :moduleDeclarations  
e              :n    :n           :n         :moduleDeclarations       :y           n                   
n              :n    :n           :n         :moduleDeclarations       :n           :moduleDeclarations  
n              :n    :n           :n         :ROOT                     :n           :program             
e              :n    :n           :n         :otherModules             :y           n                   
n              :n    :n           :n         :program                  :n           :otherModules        
<<<            :2    :DRIVERDEF   :n         :driverModule             :y           :DRIVERDEF           
n              :n    :n           :n         :program                  :n           :driverModule        
driver         :2    :DRIVER      :n         :driverModule             :y           :DRIVER              
program        :2    :PROGRAM     :n         :driverModule             :y           :PROGRAM             
>>>            :2    :DRIVERENDDEF:n         :driverModule             :y           :DRIVERENDDEF        
start          :3    :START       :n         :moduleDef                :y           :START               
n              :n    :n           :n         :driverModule             :n           :moduleDef           
declare        :4    :DECLARE     :n         :declareStmt              :y           :DECLARE             
n              :n    :n           :n         :statement                :n           :declareStmt         
var_1_         :4    :ID          :n         :idList                   :y           :ID                  
n              :n    :n           :n         :declareStmt              :n           :idList              
,              :4    :COMMA       :n         :N3                       :y           :COMMA               
n              :n    :n           :n         :idList                   :n           :N3                  
var_2_         :4    :ID          :n         :N3                       :y           :ID                  
,              :4    :COMMA       :n         :N3                       :y           :COMMA               
n              :n    :n           :n         :N3                       :n           :N3                  
var_3_         :4    :ID          :n         :N3                       :y           :ID                  
e              :n    :n           :n         :N3                       :y           n                   
n              :n    :n           :n         :N3                       :n           :N3                  
:              :4    :COLON       :n         :declareStmt              :y           :COLON               
integer        :4    :INTEGER     :n         :dataType                 :y           :INTEGER             
n              :n    :n           :n         :declareStmt              :n           :dataType            
;              :4    :SEMICOL     :n         :declareStmt              :y           :SEMICOL             
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :moduleDef                :n           :statements          
declare        :5    :DECLARE     :n         :declareStmt              :y           :DECLARE             
n              :n    :n           :n         :statement                :n           :declareStmt         
R1_abc         :5    :ID          :n         :idList                   :y           :ID                  
n              :n    :n           :n         :declareStmt              :n           :idList              
e              :n    :n           :n         :N3                       :y           n                   
n              :n    :n           :n         :idList                   :n           :N3                  
:              :5    :COLON       :n         :declareStmt              :y           :COLON               
boolean        :5    :BOOLEAN     :n         :dataType                 :y           :BOOLEAN             
n              :n    :n           :n         :declareStmt              :n           :dataType            
;              :5    :SEMICOL     :n         :declareStmt              :y           :SEMICOL             
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :statements               :n           :statements          
declare        :6    :DECLARE     :n         :declareStmt              :y           :DECLARE             
n              :n    :n           :n         :statement                :n           :declareStmt         
r2_ABC         :6    :ID          :n         :idList                   :y           :ID                  
n              :n    :n           :n         :declareStmt              :n           :idList              
e              :n    :n           :n         :N3                       :y           n                   
n              :n    :n           :n         :idList                   :n           :N3                  
:              :6    :COLON       :n         :declareStmt              :y           :COLON               
integer        :6    :INTEGER     :n         :dataType                 :y           :INTEGER             
n              :n    :n           :n         :declareStmt              :n           :dataType            
;              :6    :SEMICOL     :n         :declareStmt              :y           :SEMICOL             
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :statements               :n           :statements          
declare        :7    :DECLARE     :n         :declareStmt              :y           :DECLARE             
n              :n    :n           :n         :statement                :n           :declareStmt         
R3_abc         :7    :ID          :n         :idList                   :y           :ID                  
n              :n    :n           :n         :declareStmt              :n           :idList              
e              :n    :n           :n         :N3                       :y           n                   
n              :n    :n           :n         :idList                   :n           :N3                  
:              :7    :COLON       :n         :declareStmt              :y           :COLON               
real           :7    :REAL        :n         :dataType                 :y           :REAL                
n              :n    :n           :n         :declareStmt              :n           :dataType            
;              :7    :SEMICOL     :n         :declareStmt              :y           :SEMICOL             
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :statements               :n           :statements          
get_value      :8    :GET_VALUE   :n         :ioStmt                   :y           :GET_VALUE           
n              :n    :n           :n         :statement                :n           :ioStmt              
(              :8    :BO          :n         :ioStmt                   :y           :BO                  
var_1_         :8    :ID          :n         :ioStmt                   :y           :ID                  
)              :8    :BC          :n         :ioStmt                   :y           :BC                  
;              :8    :SEMICOL     :n         :ioStmt                   :y           :SEMICOL             
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :statements               :n           :statements          
var_2_         :9    :ID          :n         :assignmentStmt           :y           :ID                  
n              :n    :n           :n         :simpleStmt               :n           :assignmentStmt      
:=             :9    :ASSIGNOP    :n         :lvalueIDStmt             :y           :ASSIGNOP            
n              :n    :n           :n         :whichStmt                :n           :lvalueIDStmt        
10             :9    :NUM         :10        :var                      :y           :NUM                 
n              :n    :n           :n         :factor                   :n           :var                 
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :AnyTerm             
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
n              :n    :n           :n         :expression               :n           :arithmeticOrBooleanExpr
e              :n    :n           :n         :N7                       :y           n                   
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :N7                  
n              :n    :n           :n         :lvalueIDStmt             :n           :expression          
;              :9    :SEMICOL     :n         :lvalueIDStmt             :y           :SEMICOL             
n              :n    :n           :n         :assignmentStmt           :n           :whichStmt           
n              :n    :n           :n         :statement                :n           :simpleStmt          
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :statements               :n           :statements          
var_3_         :10   :ID          :n         :assignmentStmt           :y           :ID                  
n              :n    :n           :n         :simpleStmt               :n           :assignmentStmt      
:=             :10   :ASSIGNOP    :n         :lvalueIDStmt             :y           :ASSIGNOP            
n              :n    :n           :n         :whichStmt                :n           :lvalueIDStmt        
-              :10   :MINUS       :n         :expression               :y           :MINUS               
n              :n    :n           :n         :lvalueIDStmt             :n           :expression          
(              :10   :BO          :n         :expression               :y           :BO                  
6              :10   :NUM         :6         :var                      :y           :NUM                 
n              :n    :n           :n         :factor                   :n           :var                 
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :expression               :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
)              :10   :BC          :n         :expression               :y           :BC                  
;              :10   :SEMICOL     :n         :lvalueIDStmt             :y           :SEMICOL             
n              :n    :n           :n         :assignmentStmt           :n           :whichStmt           
n              :n    :n           :n         :statement                :n           :simpleStmt          
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :statements               :n           :statements          
[              :11   :SQBO        :n         :optional                 :y           :SQBO                
n              :n    :n           :n         :moduleReuseStmt          :n           :optional            
R1_abc         :11   :ID          :n         :idList                   :y           :ID                  
n              :n    :n           :n         :optional                 :n           :idList              
,              :11   :COMMA       :n         :N3                       :y           :COMMA               
n              :n    :n           :n         :idList                   :n           :N3                  
r2_ABC         :11   :ID          :n         :N3                       :y           :ID                  
,              :11   :COMMA       :n         :N3                       :y           :COMMA               
n              :n    :n           :n         :N3                       :n           :N3                  
R3_abc         :11   :ID          :n         :N3                       :y           :ID                  
e              :n    :n           :n         :N3                       :y           n                   
n              :n    :n           :n         :N3                       :n           :N3                  
]              :11   :SQBC        :n         :optional                 :y           :SQBC                
:=             :11   :ASSIGNOP    :n         :optional                 :y           :ASSIGNOP            
n              :n    :n           :n         :simpleStmt               :n           :moduleReuseStmt     
use            :11   :USE         :n         :moduleReuseStmt          :y           :USE                 
module         :11   :MODULE      :n         :moduleReuseStmt          :y           :MODULE              
compute        :11   :ID          :n         :moduleReuseStmt          :y           :ID                  
with           :11   :WITH        :n         :moduleReuseStmt          :y           :WITH                
parameters     :11   :PARAMETERS  :n         :moduleReuseStmt          :y           :PARAMETERS          
var_1_         :11   :ID          :n         :idList                   :y           :ID                  
n              :n    :n           :n         :moduleReuseStmt          :n           :idList              
,              :11   :COMMA       :n         :N3                       :y           :COMMA               
n              :n    :n           :n         :idList                   :n           :N3                  
var_2_         :11   :ID          :n         :N3                       :y           :ID                  
,              :11   :COMMA       :n         :N3                       :y           :COMMA               
n              :n    :n           :n         :N3                       :n           :N3                  
var_34         :11   :ID          :n         :N3                       :y           :ID                  
e              :n    :n           :n         :N3                       :y           n                   
n              :n    :n           :n         :N3                       :n           :N3                  
;              :11   :SEMICOL     :n         :moduleReuseStmt          :y           :SEMICOL             
n              :n    :n           :n         :statement                :n           :simpleStmt          
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :statements               :n           :statements          
e              :n    :n           :n         :statements               :y           n                   
n              :n    :n           :n         :statements               :n           :statements          
end            :14   :END         :n         :moduleDef                :y           :END                 
<<             :15   :DEF         :n         :module                   :y           :DEF                 
n              :n    :n           :n         :otherModules             :n           :module              
module         :15   :MODULE      :n         :module                   :y           :MODULE              
compute        :15   :ID          :n         :module                   :y           :ID                  
>>             :15   :ENDDEF      :n         :module                   :y           :ENDDEF              
takes          :16   :TAKES       :n         :module                   :y           :TAKES               
input          :16   :INPUT       :n         :module                   :y           :INPUT               
[              :16   :SQBO        :n         :module                   :y           :SQBO                
a              :16   :ID          :n         :input_plist              :y           :ID                  
n              :n    :n           :n         :module                   :n           :input_plist         
:              :16   :COLON       :n         :input_plist              :y           :COLON               
integer        :16   :INTEGER     :n         :dataType                 :y           :INTEGER             
n              :n    :n           :n         :input_plist              :n           :dataType            
,              :16   :COMMA       :n         :N1                       :y           :COMMA               
n              :n    :n           :n         :input_plist              :n           :N1                  
b              :16   :ID          :n         :N1                       :y           :ID                  
:              :16   :COLON       :n         :N1                       :y           :COLON               
integer        :16   :INTEGER     :n         :dataType                 :y           :INTEGER             
n              :n    :n           :n         :N1                       :n           :dataType            
,              :16   :COMMA       :n         :N1                       :y           :COMMA               
n              :n    :n           :n         :N1                       :n           :N1                  
c              :16   :ID          :n         :N1                       :y           :ID                  
:              :16   :COLON       :n         :N1                       :y           :COLON               
integer        :16   :INTEGER     :n         :dataType                 :y           :INTEGER             
n              :n    :n           :n         :N1                       :n           :dataType            
e              :n    :n           :n         :N1                       :y           n                   
n              :n    :n           :n         :N1                       :n           :N1                  
]              :16   :SQBC        :n         :module                   :y           :SQBC                
;              :16   :SEMICOL     :n         :module                   :y           :SEMICOL             
returns        :17   :RETURNS     :n         :ret                      :y           :RETURNS             
n              :n    :n           :n         :module                   :n           :ret                 
[              :17   :SQBO        :n         :ret                      :y           :SQBO                
res_1          :17   :ID          :n         :output_plist             :y           :ID                  
n              :n    :n           :n         :ret                      :n           :output_plist        
:              :17   :COLON       :n         :output_plist             :y           :COLON               
boolean        :17   :BOOLEAN     :n         :type                     :y           :BOOLEAN             
n              :n    :n           :n         :output_plist             :n           :type                
,              :17   :COMMA       :n         :N2                       :y           :COMMA               
n              :n    :n           :n         :output_plist             :n           :N2                  
res_2_a        :17   :ID          :n         :N2                       :y           :ID                  
:              :17   :COLON       :n         :N2                       :y           :COLON               
integer        :17   :INTEGER     :n         :type                     :y           :INTEGER             
n              :n    :n           :n         :N2                       :n           :type                
,              :17   :COMMA       :n         :N2                       :y           :COMMA               
n              :n    :n           :n         :N2                       :n           :N2                  
res_2__b       :17   :ID          :n         :N2                       :y           :ID                  
:              :17   :COLON       :n         :N2                       :y           :COLON               
real           :17   :REAL        :n         :type                     :y           :REAL                
n              :n    :n           :n         :N2                       :n           :type                
e              :n    :n           :n         :N2                       :y           n                   
n              :n    :n           :n         :N2                       :n           :N2                  
]              :17   :SQBC        :n         :ret                      :y           :SQBC                
;              :17   :SEMICOL     :n         :ret                      :y           :SEMICOL             
start          :18   :START       :n         :moduleDef                :y           :START               
n              :n    :n           :n         :module                   :n           :moduleDef           
declare        :19   :DECLARE     :n         :declareStmt              :y           :DECLARE             
n              :n    :n           :n         :statement                :n           :declareStmt         
b              :19   :ID          :n         :idList                   :y           :ID                  
n              :n    :n           :n         :declareStmt              :n           :idList              
e              :n    :n           :n         :N3                       :y           n                   
n              :n    :n           :n         :idList                   :n           :N3                  
:              :19   :COLON       :n         :declareStmt              :y           :COLON               
boolean        :19   :BOOLEAN     :n         :dataType                 :y           :BOOLEAN             
n              :n    :n           :n         :declareStmt              :n           :dataType            
;              :19   :SEMICOL     :n         :declareStmt              :y           :SEMICOL             
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :moduleDef                :n           :statements          
res_2_a        :20   :ID          :n         :assignmentStmt           :y           :ID                  
n              :n    :n           :n         :simpleStmt               :n           :assignmentStmt      
:=             :20   :ASSIGNOP    :n         :lvalueIDStmt             :y           :ASSIGNOP            
n              :n    :n           :n         :whichStmt                :n           :lvalueIDStmt        
-              :20   :MINUS       :n         :expression               :y           :MINUS               
n              :n    :n           :n         :lvalueIDStmt             :n           :expression          
(              :20   :BO          :n         :expression               :y           :BO                  
a              :20   :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :factor                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
*              :20   :MUL         :n         :op2                      :y           :MUL                 
n              :n    :n           :n         :N5                       :n           :op2                 
n              :n    :n           :n         :term_1                   :n           :N5                  
b              :20   :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :factor                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
n              :n    :n           :n         :N5                       :n           :factor              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :N5                       :n           :N5                  
n              :n    :n           :n         :expression               :n           :arithmeticExpr      
-              :20   :MINUS       :n         :op1                      :y           :MINUS               
n              :n    :n           :n         :N4                       :n           :op1                 
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
c              :20   :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :factor                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :N4                       :n           :term_1              
/              :20   :DIV         :n         :op2                      :y           :DIV                 
n              :n    :n           :n         :N5                       :n           :op2                 
n              :n    :n           :n         :term_1                   :n           :N5                  
5              :20   :NUM         :5         :var                      :y           :NUM                 
n              :n    :n           :n         :factor                   :n           :var                 
n              :n    :n           :n         :N5                       :n           :factor              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :N5                       :n           :N5                  
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :N4                       :n           :N4                  
)              :20   :BC          :n         :expression               :y           :BC                  
;              :20   :SEMICOL     :n         :lvalueIDStmt             :y           :SEMICOL             
n              :n    :n           :n         :assignmentStmt           :n           :whichStmt           
n              :n    :n           :n         :statement                :n           :simpleStmt          
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :statements               :n           :statements          
res_2__b       :21   :ID          :n         :assignmentStmt           :y           :ID                  
n              :n    :n           :n         :simpleStmt               :n           :assignmentStmt      
:=             :21   :ASSIGNOP    :n         :lvalueIDStmt             :y           :ASSIGNOP            
n              :n    :n           :n         :whichStmt                :n           :lvalueIDStmt        
(              :21   :BO          :n         :factor                   :y           :BO                  
n              :n    :n           :n         :term_1                   :n           :factor              
(              :21   :BO          :n         :factor                   :y           :BO                  
n              :n    :n           :n         :term_1                   :n           :factor              
res_2_a        :21   :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :factor                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
+              :21   :PLUS        :n         :op1                      :y           :PLUS                
n              :n    :n           :n         :N4                       :n           :op1                 
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
a              :21   :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :factor                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :N4                       :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :N4                       :n           :N4                  
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :AnyTerm             
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
n              :n    :n           :n         :factor                   :n           :arithmeticOrBooleanExpr
e              :n    :n           :n         :N7                       :y           n                   
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :N7                  
)              :21   :BC          :n         :factor                   :y           :BC                  
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
*              :21   :MUL         :n         :op2                      :y           :MUL                 
n              :n    :n           :n         :N5                       :n           :op2                 
n              :n    :n           :n         :term_1                   :n           :N5                  
12             :21   :NUM         :12        :var                      :y           :NUM                 
n              :n    :n           :n         :factor                   :n           :var                 
n              :n    :n           :n         :N5                       :n           :factor              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :N5                       :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
+              :21   :PLUS        :n         :op1                      :y           :PLUS                
n              :n    :n           :n         :N4                       :n           :op1                 
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
0.223400       :21   :RNUM        :0.223400  :var                      :y           :RNUM                
n              :n    :n           :n         :factor                   :n           :var                 
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :N4                       :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :N4                       :n           :N4                  
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :AnyTerm             
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
n              :n    :n           :n         :factor                   :n           :arithmeticOrBooleanExpr
e              :n    :n           :n         :N7                       :y           n                   
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :N7                  
)              :21   :BC          :n         :factor                   :y           :BC                  
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
/              :21   :DIV         :n         :op2                      :y           :DIV                 
n              :n    :n           :n         :N5                       :n           :op2                 
n              :n    :n           :n         :term_1                   :n           :N5                  
13             :21   :NUM         :13        :var                      :y           :NUM                 
n              :n    :n           :n         :factor                   :n           :var                 
n              :n    :n           :n         :N5                       :n           :factor              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :N5                       :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :AnyTerm             
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
n              :n    :n           :n         :expression               :n           :arithmeticOrBooleanExpr
e              :n    :n           :n         :N7                       :y           n                   
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :N7                  
n              :n    :n           :n         :lvalueIDStmt             :n           :expression          
;              :21   :SEMICOL     :n         :lvalueIDStmt             :y           :SEMICOL             
n              :n    :n           :n         :assignmentStmt           :n           :whichStmt           
n              :n    :n           :n         :statement                :n           :simpleStmt          
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :statements               :n           :statements          
b              :22   :ID          :n         :assignmentStmt           :y           :ID                  
n              :n    :n           :n         :simpleStmt               :n           :assignmentStmt      
:=             :22   :ASSIGNOP    :n         :lvalueIDStmt             :y           :ASSIGNOP            
n              :n    :n           :n         :whichStmt                :n           :lvalueIDStmt        
(              :22   :BO          :n         :factor                   :y           :BO                  
n              :n    :n           :n         :term_1                   :n           :factor              
(              :22   :BO          :n         :factor                   :y           :BO                  
n              :n    :n           :n         :term_1                   :n           :factor              
a              :22   :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :factor                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :AnyTerm             
<=             :22   :LE          :n         :relationalOp             :y           :LE                  
n              :n    :n           :n         :N8                       :n           :relationalOp        
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
b              :22   :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :factor                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :N8                       :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :N8                       :n           :N8                  
n              :n    :n           :n         :factor                   :n           :arithmeticOrBooleanExpr
e              :n    :n           :n         :N7                       :y           n                   
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :N7                  
)              :22   :BC          :n         :factor                   :y           :BC                  
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :AnyTerm             
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
n              :n    :n           :n         :factor                   :n           :arithmeticOrBooleanExpr
AND            :22   :AND         :n         :logicalOp                :y           :AND                 
n              :n    :n           :n         :N7                       :n           :logicalOp           
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :N7                  
c              :22   :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :factor                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
n              :n    :n           :n         :N7                       :n           :AnyTerm             
>              :22   :GE          :n         :relationalOp             :y           :GE                  
n              :n    :n           :n         :N8                       :n           :relationalOp        
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
a              :22   :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :factor                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :N8                       :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :N8                       :n           :N8                  
e              :n    :n           :n         :N7                       :y           n                   
n              :n    :n           :n         :N7                       :n           :N7                  
)              :22   :BC          :n         :factor                   :y           :BC                  
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :AnyTerm             
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
n              :n    :n           :n         :expression               :n           :arithmeticOrBooleanExpr
OR             :22   :OR          :n         :logicalOp                :y           :OR                  
n              :n    :n           :n         :N7                       :n           :logicalOp           
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :N7                  
(              :22   :BO          :n         :factor                   :y           :BO                  
n              :n    :n           :n         :term_1                   :n           :factor              
a              :22   :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :factor                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :AnyTerm             
<              :22   :LT          :n         :relationalOp             :y           :LT                  
n              :n    :n           :n         :N8                       :n           :relationalOp        
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
0              :22   :NUM         :0         :var                      :y           :NUM                 
n              :n    :n           :n         :factor                   :n           :var                 
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :N8                       :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :N8                       :n           :N8                  
n              :n    :n           :n         :factor                   :n           :arithmeticOrBooleanExpr
e              :n    :n           :n         :N7                       :y           n                   
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :N7                  
)              :22   :BC          :n         :factor                   :y           :BC                  
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
n              :n    :n           :n         :N7                       :n           :AnyTerm             
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
e              :n    :n           :n         :N7                       :y           n                   
n              :n    :n           :n         :N7                       :n           :N7                  
n              :n    :n           :n         :lvalueIDStmt             :n           :expression          
;              :22   :SEMICOL     :n         :lvalueIDStmt             :y           :SEMICOL             
n              :n    :n           :n         :assignmentStmt           :n           :whichStmt           
n              :n    :n           :n         :statement                :n           :simpleStmt          
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :statements               :n           :statements          
declare        :23   :DECLARE     :n         :declareStmt              :y           :DECLARE             
n              :n    :n           :n         :statement                :n           :declareStmt         
a              :23   :ID          :n         :idList                   :y           :ID                  
n              :n    :n           :n         :declareStmt              :n           :idList              
e              :n    :n           :n         :N3                       :y           n                   
n              :n    :n           :n         :idList                   :n           :N3                  
:              :23   :COLON       :n         :declareStmt              :y           :COLON               
integer        :23   :INTEGER     :n         :dataType                 :y           :INTEGER             
n              :n    :n           :n         :declareStmt              :n           :dataType            
;              :23   :SEMICOL     :n         :declareStmt              :y           :SEMICOL             
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :statements               :n           :statements          
res_1          :24   :ID          :n         :assignmentStmt           :y           :ID                  
n              :n    :n           :n         :simpleStmt               :n           :assignmentStmt      
:=             :24   :ASSIGNOP    :n         :lvalueIDStmt             :y           :ASSIGNOP            
n              :n    :n           :n         :whichStmt                :n           :lvalueIDStmt        
(              :24   :BO          :n         :factor                   :y           :BO                  
n              :n    :n           :n         :term_1                   :n           :factor              
(              :24   :BO          :n         :factor                   :y           :BO                  
n              :n    :n           :n         :term_1                   :n           :factor              
b              :24   :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :factor                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :AnyTerm             
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
n              :n    :n           :n         :factor                   :n           :arithmeticOrBooleanExpr
AND            :24   :AND         :n         :logicalOp                :y           :AND                 
n              :n    :n           :n         :N7                       :n           :logicalOp           
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :N7                  
c              :24   :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :factor                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
n              :n    :n           :n         :N7                       :n           :AnyTerm             
==             :24   :EQ          :n         :relationalOp             :y           :EQ                  
n              :n    :n           :n         :N8                       :n           :relationalOp        
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
b              :24   :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :factor                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :N8                       :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :N8                       :n           :N8                  
e              :n    :n           :n         :N7                       :y           n                   
n              :n    :n           :n         :N7                       :n           :N7                  
)              :24   :BC          :n         :factor                   :y           :BC                  
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :AnyTerm             
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
n              :n    :n           :n         :factor                   :n           :arithmeticOrBooleanExpr
OR             :24   :OR          :n         :logicalOp                :y           :OR                  
n              :n    :n           :n         :N7                       :n           :logicalOp           
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :N7                  
(              :24   :BO          :n         :factor                   :y           :BO                  
n              :n    :n           :n         :term_1                   :n           :factor              
b              :24   :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :factor                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :AnyTerm             
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
n              :n    :n           :n         :factor                   :n           :arithmeticOrBooleanExpr
AND            :24   :AND         :n         :logicalOp                :y           :AND                 
n              :n    :n           :n         :N7                       :n           :logicalOp           
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :N7                  
(              :24   :BO          :n         :factor                   :y           :BO                  
n              :n    :n           :n         :term_1                   :n           :factor              
a              :24   :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :factor                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :AnyTerm             
<=             :24   :LE          :n         :relationalOp             :y           :LE                  
n              :n    :n           :n         :N8                       :n           :relationalOp        
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
c              :24   :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :factor                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
n              :n    :n           :n         :term_1                   :n           :factor              
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :N8                       :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :N8                       :n           :N8                  
n              :n    :n           :n         :factor                   :n           :arithmeticOrBooleanExpr
e              :n    :n           :n         :N7                       :y           n                   
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :N7                  
)              :24   :BC          :n         :factor                   :y           :BC                  
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
n              :n    :n           :n         :N7                       :n           :AnyTerm             
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
e              :n    :n           :n         :N7                       :y           n                   
n              :n    :n           :n         :N7                       :n           :N7                  
)              :24   :BC          :n         :factor                   :y           :BC                  
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
n              :n    :n           :n         :N7                       :n           :AnyTerm             
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
e              :n    :n           :n         :N7                       :y           n                   
n              :n    :n           :n         :N7                       :n           :N7                  
)              :24   :BC          :n         :factor                   :y           :BC                  
n              :n    :n           :n         :arithmeticExpr           :n           :term_1              
e              :n    :n           :n         :N5                       :y           n                   
n              :n    :n           :n         :term_1                   :n           :N5                  
n              :n    :n           :n         :AnyTerm                  :n           :arithmeticExpr      
e              :n    :n           :n         :N4                       :y           n                   
n              :n    :n           :n         :arithmeticExpr           :n           :N4                  
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :AnyTerm             
e              :n    :n           :n         :N8                       :y           n                   
n              :n    :n           :n         :AnyTerm                  :n           :N8                  
n              :n    :n           :n         :expression               :n           :arithmeticOrBooleanExpr
e              :n    :n           :n         :N7                       :y           n                   
n              :n    :n           :n         :arithmeticOrBooleanExpr  :n           :N7                  
n              :n    :n           :n         :lvalueIDStmt             :n           :expression          
;              :24   :SEMICOL     :n         :lvalueIDStmt             :y           :SEMICOL             
n              :n    :n           :n         :assignmentStmt           :n           :whichStmt           
n              :n    :n           :n         :statement                :n           :simpleStmt          
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :statements               :n           :statements          
print          :27   :PRINT       :n         :ioStmt                   :y           :PRINT               
n              :n    :n           :n         :statement                :n           :ioStmt              
(              :27   :BO          :n         :ioStmt                   :y           :BO                  
res_1          :27   :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :ioStmt                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
)              :27   :BC          :n         :ioStmt                   :y           :BC                  
;              :27   :SEMICOL     :n         :ioStmt                   :y           :SEMICOL             
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :statements               :n           :statements          
e              :n    :n           :n         :statements               :y           n                   
n              :n    :n           :n         :statements               :n           :statements          
end            :28   :END         :n         :moduleDef                :y           :END                 
n              :n    :n           :n         :program                  :n           :otherModules        
e              :n    :n           :n         :otherModules             :y           n                   
n              :n    :n           :n         :otherModules             :n           :otherModules        