lexCurrentNode :lNo  :token       :valIfNo   :pNode                    :IsLeaf(y/n) :nodeSymbol          
e              :n    :n           :n         :moduleDeclarations       :y           n                   
n              :n    :n           :n         :program                  :n           :moduleDeclarations  
n              :n    :n           :n         :ROOT                     :n           :program             
e              :n    :n           :n         :otherModules             :y           n                   
n              :n    :n           :n         :program                  :n           :otherModules        
<<<            :1    :DRIVERDEF   :n         :driverModule             :y           :DRIVERDEF           
n              :n    :n           :n         :program                  :n           :driverModule        
driver         :1    :DRIVER      :n         :driverModule             :y           :DRIVER              
program        :1    :PROGRAM     :n         :driverModule             :y           :PROGRAM             
>>>            :1    :DRIVERENDDEF:n         :driverModule             :y           :DRIVERENDDEF        
start          :2    :START       :n         :moduleDef                :y           :START               
n              :n    :n           :n         :driverModule             :n           :moduleDef           
declare        :3    :DECLARE     :n         :declareStmt              :y           :DECLARE             
n              :n    :n           :n         :statement                :n           :declareStmt         
v_1_2_3        :3    :ID          :n         :idList                   :y           :ID                  
n              :n    :n           :n         :declareStmt              :n           :idList              
e              :n    :n           :n         :N3                       :y           n                   
n              :n    :n           :n         :idList                   :n           :N3                  
:              :3    :COLON       :n         :declareStmt              :y           :COLON               
integer        :3    :INTEGER     :n         :dataType                 :y           :INTEGER             
n              :n    :n           :n         :declareStmt              :n           :dataType            
;              :3    :SEMICOL     :n         :declareStmt              :y           :SEMICOL             
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :moduleDef                :n           :statements          
get_value      :4    :GET_VALUE   :n         :ioStmt                   :y           :GET_VALUE           
n              :n    :n           :n         :statement                :n           :ioStmt              
(              :4    :BO          :n         :ioStmt                   :y           :BO                  
v_1_2_3        :4    :ID          :n         :ioStmt                   :y           :ID                  
)              :4    :BC          :n         :ioStmt                   :y           :BC                  
;              :4    :SEMICOL     :n         :ioStmt                   :y           :SEMICOL             
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :statements               :n           :statements          
declare        :5    :DECLARE     :n         :declareStmt              :y           :DECLARE             
n              :n    :n           :n         :statement                :n           :declareStmt         
result_        :5    :ID          :n         :idList                   :y           :ID                  
n              :n    :n           :n         :declareStmt              :n           :idList              
e              :n    :n           :n         :N3                       :y           n                   
n              :n    :n           :n         :idList                   :n           :N3                  
:              :5    :COLON       :n         :declareStmt              :y           :COLON               
integer        :5    :INTEGER     :n         :dataType                 :y           :INTEGER             
n              :n    :n           :n         :declareStmt              :n           :dataType            
;              :5    :SEMICOL     :n         :declareStmt              :y           :SEMICOL             
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :statements               :n           :statements          
[              :6    :SQBO        :n         :optional                 :y           :SQBO                
n              :n    :n           :n         :moduleReuseStmt          :n           :optional            
result_        :6    :ID          :n         :idList                   :y           :ID                  
n              :n    :n           :n         :optional                 :n           :idList              
e              :n    :n           :n         :N3                       :y           n                   
n              :n    :n           :n         :idList                   :n           :N3                  
]              :6    :SQBC        :n         :optional                 :y           :SQBC                
:=             :6    :ASSIGNOP    :n         :optional                 :y           :ASSIGNOP            
n              :n    :n           :n         :simpleStmt               :n           :moduleReuseStmt     
use            :6    :USE         :n         :moduleReuseStmt          :y           :USE                 
module         :6    :MODULE      :n         :moduleReuseStmt          :y           :MODULE              
square         :6    :ID          :n         :moduleReuseStmt          :y           :ID                  
with           :6    :WITH        :n         :moduleReuseStmt          :y           :WITH                
parameters     :6    :PARAMETERS  :n         :moduleReuseStmt          :y           :PARAMETERS          
v_1_2_3        :6    :ID          :n         :idList                   :y           :ID                  
n              :n    :n           :n         :moduleReuseStmt          :n           :idList              
e              :n    :n           :n         :N3                       :y           n                   
n              :n    :n           :n         :idList                   :n           :N3                  
;              :6    :SEMICOL     :n         :moduleReuseStmt          :y           :SEMICOL             
n              :n    :n           :n         :statement                :n           :simpleStmt          
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :statements               :n           :statements          
print          :7    :PRINT       :n         :ioStmt                   :y           :PRINT               
n              :n    :n           :n         :statement                :n           :ioStmt              
(              :7    :BO          :n         :ioStmt                   :y           :BO                  
result         :7    :ID          :n         :var                      :y           :ID                  
n              :n    :n           :n         :ioStmt                   :n           :var                 
e              :n    :n           :n         :whichID                  :y           n                   
n              :n    :n           :n         :var                      :n           :whichID             
)              :7    :BC          :n         :ioStmt                   :y           :BC                  
;              :7    :SEMICOL     :n         :ioStmt                   :y           :SEMICOL             
n              :n    :n           :n         :statements               :n           :statement           
n              :n    :n           :n         :statements               :n           :statements          
e              :n    :n           :n         :statements               :y           n                   
n              :n    :n           :n         :statements               :n           :statements          
end            :8    :END         :n         :moduleDef                :y           :END                 
e              :n    :n           :n         :otherModules             :y           n                   
n              :n    :n           :n         :program                  :n           :otherModules        